service/models/shopcart.py
service/routes.py
tests/test_routes.py

Made the following changes:
- Added create shopcarts endpoint in `routes.py`
- Added a test case for create shopcarts endpoint

Added create shopcarts endpoint

---

service/models/item.py
service/models/shopcart.py
service/routes.py
tests/factories.py
tests/test_item.py
tests/test_routes.py
tests/test_shopcart.py

Changes made:
* Made sure that the server itself was making the create/update and that everything was using ISO format
* Misc. typos and doc string changes

Fix-audit-dates

---

service/routes.py
tests/test_routes.py
tests/test_shopcart.py

Changes made:
* Reverted code from PR #21 
* Added update shopcart functionality

11 - revert PR changes from #21, add Update Shopcart feature

---

service/models/item.py
service/routes.py
tests/factories.py
tests/test_routes.py

Changes made:
* Added functionality to add items to a shopcart
* Added tests for that functionality
Note: make sure to fix the TODO (regarding the location of the get) after we implement that

#1 - completed add item functionality

---

service/routes.py
tests/factories.py
tests/test_routes.py

• Added view shopcart route and respective test
• Created a helper function to add items in shopcart (_create_items)

completed view-shopcart-contents

---

service/routes.py
tests/test_routes.py

Made the following changes:
- Added read an item from shopcart endpoint in `routes.py`
- Renamed get_items to list_items in `routes.py`
- Added test cases for read an item endpoint in `test_routes.py`
- Modified _create_items to return created items list in `test_routes.py`
- Uncommented the todo parts and modified some variable names of test_add_item in `test_routes.py`

Add read items

---

service/routes.py
tests/test_routes.py

Made the following changes:
- Added delete items endpoint in `routes.py`
- Modified read items endpoint in `routes.py`
- Added test cases for delete item endpoint in `test_routes.py`
- Added test case for deleting non-existing shopcarts in `test_routes.py`

Add delete items

---

service/routes.py
tests/test_routes.py

Changes made:
* Added update endpoint to `routes.py`
* Added test case in `test_routes.py`

#4 - added update endpoint for item resources

---

.github/ISSUE_TEMPLATE/workflows/ci.yml
.github/workflows/ci.yml
README.md
service/routes.py

- Added a ci.yml file at `.github/workflows/ci.yml`

Added ci.yml file

---

service/models/shopcart.py
service/routes.py
tests/test_routes.py
tests/test_shopcart.py

Changes made:
* Confirmed model's ability to query by filter by customer_name
* Added filtering by name to the `list_shopcarts` function so that a GET can be made with query parameters

#33 - added query filtering by customer name for shopcarts GET

---

service/models/item.py
service/routes.py
tests/test_item.py
tests/test_routes.py

Changes made:
* Added query support (by name) for finding items within a specific shopcarts within model
* Added query support (by name) for listing items within a specific shopcarts within the GET method in `routes.py`
* Added relevant tests for above additions

#34 - added query support for item names within shopcart

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml

Changes made:
* Added codecov upload to ci.yml
* Added codecov badge to README.md

#39 - Adding Codecov support to Actions workflow

---

service/models/shopcart.py
service/routes.py
tests/test_routes.py
tests/test_shopcart.py

• shopcart.py: Refactored clear_shopcart() to delete items and prevent NULL violations.
• routes.py: Added PUT /shopcarts/<id>/empty endpoint to clear shopcart items.
• test_routes.py: Added tests for empty endpoint, ensuring idempotency.
• test_shopcart.py: Added test for clear_shopcart() to confirm item deletion.

Action Route for Emptying a Shopcart

---

service/models/item.py
tests/factories.py
tests/test_item.py
tests/test_shopcart.py

Changes made:
* Added `is_urgent` attribute to model
* Updated test cases for serializing item/testing shopcart
*

37 - Add is_urgent attribute to model

---

service/routes.py
tests/test_routes.py

• routes.py: Add endpoints to mark/unmark items as urgent in a shopcart.
• test_routes.py: Add tests for marking, unmarking, and idempotency of urgent flag.

Action Route for marking Item as urgent/nonurgent in Shopcart

---

Dockerfile
Makefile
k8s/deployment.yaml
k8s/ingress.yaml
k8s/postgres/configmap.yaml
k8s/postgres/pvc.yaml
k8s/postgres/secret.yaml
k8s/postgres/service.yaml
k8s/postgres/statefulset.yaml
k8s/pv.yaml
k8s/service.yaml
service/routes.py
tests/test_routes.py

Changes made:
* made k8s manifest files
* added health check to `routes.py`
* Changed `make cluster` to also build, tag, push to container registry
* Note: make sure to run `make deploy` to deploy after that

Kubernetes Deploy

---

Makefile

Changes made:
* Fixed typo for make deploy
* fixed host issue not showing up for container registery

Kubernetes deploy: fixed typo and host issue

---

Dockerfile
features/environment.py
features/shopcarts.feature
features/steps/steps.py
features/steps/web_steps.py
poetry.lock
pyproject.toml

Changes made:
* Added poetry dependencies for behave things
* Note: moved from python-slim to the python slim on quay.io
* Added steps, environment, basic feature file with shopcart data
* Added step to take shopcarts/items from the feature file background and send it to the application

Setting up BDD testing

---

service/routes.py
tests/test_routes.py

Changes made:
* Changed UI to be served from index endpoint
* Change test to use index endpoint to verify UI served

Fixed UI route to be the main endpoint

---

features/shopcarts.feature
service/static/index.html
service/static/js/rest_api.js

Changes Made:
* Added UI components for Create and clear, along with fields for customer name
* Added JS to accomodate create components
* Added `behave` test to test crate (remember TODO to uncomment after Retrieve functionality added to UI)

added create functionality to ui

---

features/shopcarts.feature
features/steps/web_steps.py
service/static/index.html
service/static/js/rest_api.js

• Added GET fuctionality to web UI.

Added Get Functionality to UI (Retrieve)

---

features/shopcarts.feature
service/models/shopcart.py
service/routes.py
service/static/index.html
service/static/js/rest_api.js

Changes made:
* Fixed some issues with the actual update endpoint that was just noticed (had to do with deserialization)
* Added update ui components
* Added `behave` test case for update functionality

Add Update functionality to UI

---

features/shopcarts.feature
features/steps/web_steps.py
service/static/index.html
service/static/js/rest_api.js

Changes made:
* Added UI + JS for empty action
* Added to `web_steps.py` to find a customer name and copy its ID from the list table
* Added empty BDD test

Add Empty Action Functionality to UI

---

features/shopcarts.feature
service/static/index.html
service/static/js/rest_api.js

• Added a Delete button in the UI which delete a shopcart by id.

Added Delete Functionality to UI

---

features/shopcarts.feature
service/static/index.html
service/static/js/rest_api.js

Changes made:
* Added query UI components and JS for it
* Added `behave` tests to test the above feature in BBD way

Added Query Capability to the UI

---

.vscode/settings.json
features/steps/steps.py
features/steps/web_steps.py
service/__init__.py
service/common/error_handlers.py
service/routes.py
service/static/js/rest_api.js
tests/test_routes.py

Changes made:
* Refactored rest of routes.py to use flask-restx instead
* The only changes made in the test for routes is in error message strings during assertion
* Cleaned up utility functions within routes.py
* Changed prefix to /app and changed ui file back to root

Refactor to Flask-RestX for Item + Shopcart Get/Delete/Update/Empty Endpoints

---

service/common/error_handlers.py

Cleaned up extra error handlers

---

.tekton/pipeline.yaml
.tekton/tasks.yaml
.tekton/workspace.yaml

Added .tekton/
- pipeline.yaml
- workspace.yaml
- tasks.yaml
Covers pipeline for cloning, testing, linting the application code.

OpenShift pipeline created and added .tekton/ yaml files

---

.tekton/pipeline.yaml

Changes made:
* Changed the pipeline.yaml using the pipeline builder to add the deploy and build components

Openshift Pipeline - added build/deploy to pipeline
